name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        d=$(date +'%Y-%m-%d')
        echo $d
        curl -X "GET" \
        "https://api.amber.com.au/v1/sites/$AMBER_SITE_ID/usage?startDate=$d&endDate=$d&resolution=30" \
        -H "accept: application/json" \
        -H "Authorization: Bearer $AMBER_API_KEY" > events.json

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

    - name: build and publish
      env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        ./run.sh
